defaults:

  npm-install: &npm-install
    run:
      name: "Install npm deps"
      command: |
        npm install --no-package-lock

  lint: &lint
    run:
      name: "Lint source code"
      command: |
        npm run lint

  build-wabt: &build-wabt
    run:
      name: "Build wabt"
      command: |
        ls
        git submodule update --init --recursive
        cd tools/wabt
        cmake -DBUILD_TESTS=OFF
        make -j8

  validate-build: &validate-build
    run:
      name: "Validate build artifacts were correctly included"
      command: |
        npm run build:validate

  build-cpp: &build-cpp
    run:
      name: "Build C++ evm2wasm"
      command: |
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j4
  
  state-tests: &state-tests
    run:
      name: "run state tests"
      command: |
        /usr/local/go/bin/go build check/main.go
        PATH=$PATH:/home/builder/test
        ./check/check test-suite

  vm-tests: &vm-tests
    run:
      name: "Run ethereum VM tests"
      command: |
        npm run vmTests

  clone-cpp-eth: &clone-cpp-eth
    run:
      name: "Clone cpp-ethereum and hera"
      working_directory: ~/
      # to fetch Hera branch that does evm2wasm.js --trace:
      # cd hera
      # git fetch origin evm2wasm-trace
      # git checkout evm2wasm-trace
      command: |
        git clone https://github.com/ethereum/cpp-ethereum --branch ewasm-json-trace --single-branch
        cd cpp-ethereum
        git submodule update --init --recursive

  build-cpp-eth: &build-cpp-eth
    run:
      name: "Build cpp-ethereum and hera"
      working_directory: ~/
      command: |
        mkdir -p build
        cd build
        cmake ../cpp-ethereum -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHERA=ON -DHERA_DEBUGGING=ON -DHERA_EVM2WASM=ON
        make -j4

  print-cpp-hera-version: &print-cpp-hera-version
    run:
      name: "Using cpp-ethereum and Hera versions:"
      working_directory: ~/
      command: |
        cd cpp-ethereum
        echo "cpp-ethereum branch: $(git rev-parse --abbrev-ref HEAD)  commit: $(git rev-parse HEAD)"
        cd hera
        echo "hera branch: $(git rev-parse --abbrev-ref HEAD)  commit: $(git rev-parse HEAD)"

  clone-tests: &clone-tests
    run:
      name: "Clone tests repo"
      command: |
        git clone https://github.com/ethereum/tests test-suite

  cli-tests: &cli-tests
    run:
      name: "Basic CLI validation"
      working_directory: ~/evm2wasm
      command: |
        bin/evm2wasm.js 600160020200 --trace
        build/tools/evm2wasm/evm2wasm <(echo "600160020200")

  state-test-steps: &state-test-steps
    - checkout
    - *npm-install
    - *lint
    - *clone-tests
    - *build-wabt
    - *validate-build
      #- *build-cpp
      #- *cli-tests # weird chars mess up the console
      #- *vm-tests # vm-tests temporarily disabled until ewasm-kernel is fixed
    - *clone-cpp-eth
    - *build-cpp-eth
    - *state-tests
    # - *print-cpp-hera-version

version: 2
jobs:
  # to run this using local circleci tool, rename Ewasm-Tests to `build` then do `circleci build -c circle.yml`
  build:
    environment:
      GOPATH: /home/builder/go
    working_directory: ~/evm2wasm
    docker:
      - image: jwasinger/evm2wasm-circleci
    steps: *state-test-steps

workflows:
  version: 2
  evm2wasm-build:
    jobs:
       - build
